/* 
 * Copyright (C) 2015 Luis Chávez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.luischavez.levsym.modulos.widget;

import com.github.luischavez.levsym.modulos.funcion.Log;

/**
 *
 * @author Luis
 */
public class WCalendar extends javax.swing.JPanel {

    private Thread t;

    /** Creates new form WCalendar */
    public WCalendar() {
        initComponents();

        /*
         * Crea un nuevo Thread para el Widget
         */
        t = new Thread(new Runnable() {

            @Override
            public void run() {
                while(true){
                    SetTime();
                    try {
                        t.sleep(60000 * 60); //Detiene el Thread por 60 minutos
                    } catch (InterruptedException ex) {
                        Log.SaveLog(ex.toString());
                    }
                }
            }
        });
        t.start(); //inicia el Thread
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCalendar1 = new com.toedter.calendar.JCalendar();

        setMaximumSize(new java.awt.Dimension(204, 175));
        setMinimumSize(new java.awt.Dimension(204, 175));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.5;
        gridBagConstraints.weighty = 1.5;
        add(jCalendar1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    // End of variables declaration//GEN-END:variables

    /**
     * Selecciona el tiempo del sistema
     * y lo cambia en el calendario
     **/
    private void SetTime() {
        this.jCalendar1.setCalendar(java.util.Calendar.getInstance());
    }

}
