/* 
 * Copyright (C) 2015 Luis Chávez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.luischavez.levsym.modulos.herramientas;

import com.github.luischavez.levsym.modulos.funcion.Log;
import com.github.luischavez.levsym.modulos.funcion.Sql;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Luis
 */
public class Shell extends javax.swing.JPanel {

    /**
     * Crea una nueva conexion
     *
     */
    private Statement Instruccion;

    /**
     * Creates new form Shell
     */
    public Shell() {
        initComponents();

        /*
         * Estableze la configuracion para la conexion
         */
        try {
            Instruccion = Sql.connection.createStatement();
        } catch (SQLException ex) {
            Log.SaveLog(ex.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 102, 204));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText(">>");
        jTextField1.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        //Si presiona Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Boolean state = Instruccion.execute(jTextField2.getText());
                ResultSet resultSet = Instruccion.getResultSet();
                ResultSetMetaData metaData = null;
                int[] SizeColumns = null;
                if (state) {
                    metaData = resultSet.getMetaData();
                    SizeColumns = new int[metaData.getColumnCount()];
                }
                int ColumnLength = 0;

                if (!(resultSet == null)) { //Si no es nulo
                    while (resultSet.next()) {
                        for (int x = 0; x < metaData.getColumnCount(); x++) {
                            ColumnLength = metaData.getColumnName(x + 1).length();
                            if (SizeColumns[x] < ColumnLength) {
                                SizeColumns[x] = ColumnLength;
                            }
                            ColumnLength = resultSet.getObject(x + 1).toString().length();
                            if (SizeColumns[x] < ColumnLength) {
                                SizeColumns[x] = ColumnLength;
                            }
                        }
                    }
                    resultSet.beforeFirst();
                    for (int x = 0; x < metaData.getColumnCount(); x++) {
                        for (int z = 0; z < SizeColumns[x] + 2; z++) {
                            jTextArea1.append("_");
                        }
                    }
                    jTextArea1.append("\n");
                    for (int x = 0; x < metaData.getColumnCount(); x++) {
                        jTextArea1.append("|" + metaData.getColumnName(x + 1));
                        for (int y = 0; y < SizeColumns[x] - metaData.getColumnName(x + 1).length(); y++) {
                            jTextArea1.append(" ");
                        }
                        jTextArea1.append("|");
                    }
                    jTextArea1.append("\n");
                    while (resultSet.next()) { //Obtiene el siguiente resultado
                        //Recorre las columnas del resultado
                        for (int x = 0; x < metaData.getColumnCount(); x++) {
                            //Muestra el resultado por pantalla
                            jTextArea1.append("|" + resultSet.getObject(x + 1).toString());
                            for (int y = 0; y < SizeColumns[x] - resultSet.getObject(x + 1).toString().length(); y++) {
                                jTextArea1.append(" ");
                            }
                            jTextArea1.append("|");
                        }
                        jTextArea1.append("\n");
                        for (int x = 0; x < metaData.getColumnCount(); x++) {
                            for (int z = 0; z < SizeColumns[x] + 2; z++) {
                                jTextArea1.append("-");
                            }
                        }
                        jTextArea1.append("\n");
                    }
                } else {
                    //Muestra el estado de la ejecucion
                    jTextArea1.append("Execute: " + !state + "\n");
                }
            } catch (SQLException ex) {
                //Muestra el error
                jTextArea1.append("Warning: " + ex + "\n");
                Log.SaveLog(ex.toString());
            }
        }
    }//GEN-LAST:event_jTextField2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
